generator:
  class: sfDoctrineGenerator
  param:
    model_class:           classtype
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          classtype
    with_doctrine_route:   true
    actions_base_class:    sfActions
    # extra: [show, print, export]

    config:
      actions:
      fields:
        type_name: { label: Tipo de clase}
      list:
        title: Categorias de clases
        display: [ type_name ]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
      show:    ~
